### ISSUE TITLE
Problem with mockings

### ISSUE THREAD

**Issue by aalepis** [archan937/mecks_unit#1]
Hey!
I want to use this library though I am not entirely sure it fit my purpose.
I have created the below modules to show you my case:
```
defmodule Mocked do
  def func() do
    Mocked.ModuleA.call_module_b_func()
  end

  def func2() do
    Mocked.ModuleB.module_a_func()
  end
end
```

```
defmodule Mocked.ModuleA do
  alias Mocked.ModuleB

  def module_a_func() do
    :returns_from_module_a
  end

  def call_module_b_func() do
    ModuleB.module_b_func()
  end
end 

```
```
defmodule Mocked.ModuleB do
  alias Mocked.ModuleA

  def module_b_func() do
    :returns_from_module_b
  end

  def module_a_func() do
    ModuleA.module_a_func()
  end
end

```

and I try to run the following test which fails if I run both tests but succeeds when I run them separately. 

```
defmodule MockedTest do
  use ExUnit.Case
  use MecksUnit.Case

  defmock Mocked.ModuleB do
    def module_b_func() do
      :returns_from_mocking
    end
  end

  defmock Mocked.ModuleA do
    def module_a_func() do
      :returns_from_mocking
    end
  end

  mocked_test "mocking works" do
    assert Mocked.func() === :returns_from_mocking
  end

  mocked_test "mocking works again" do
    assert Mocked.func2() === :returns_from_mocking
  end
end

```

Do you have any insights on this problem? 

Thanks! 🙂

**Comment by archan937** [comment]
Hey, there. I'll take a look at it this weekend

**Comment by aalepis** [comment]
Hey again, have given this any thought?

**Comment by archan937** [comment]
I guess I have read your description incorrectly. The resulting behaviour is as expected. See also the README:

> Please note that the defined mock modules only apply to the first mocked_test encountered. So they are isolated (despite of :meck having an unfortunate global effect) as MecksUnit takes care of it. Also, non-matching function heads within the mock module will result in invoking the original module function as well.

I had to change

```
assert Mocked.func2() === : returns_from_mocking
```

to 

```
assert Mocked.func2() === :returns_from_module_a
```

to get the build succeeding (see: https://travis-ci.org/archan937/mecks_unit)

**Comment by aalepis** [comment]
I guess missed that part :frowning_face: 
Thanks for explaining!

**Comment by aalepis** [comment]
Hey again @archan937 , can I propose as a feature for the library to give the option of choosing whether  to apply the mocks to all the `mocked_test`s or just the first?

**Comment by archan937** [comment]
Sure. I will add this later on this week. Keep an eye out! ;)

**Comment by aalepis** [comment]
That's great! 
Thanks a lot 🙂

**Comment by archan937** [comment]
Hey, @aalepis . It is a week later than promised but I have added the ability to "preserve" mock module definitions for the rest of the test case.

This has been release in [MecksUnit v0.1.7](https://hex.pm/packages/mecks_unit/0.1.7) :)

For more information, please see https://github.com/archan937/mecks_unit#define-mock-module-for-entire-test-case and also https://github.com/archan937/mecks_unit/commit/421901711a9ab4a7ae4a1585efd2b46446f7517e

**Comment by aalepis** [comment]
Thank you very much @archan937, I really appreciate it!

**Comment by archan937** [comment]
You're welcome, @aalepis. I hope it can help you further ;)
