### ISSUE TITLE
Mocks are not found when running "mix test" with non-path arguments

### ISSUE THREAD

**Issue by hrubi** [archan937/mecks_unit#4]
Run tests with
```
mix test --trace
```
In that case, `mix` runs all the tests with more details. MecksUnit checks `System.argv()` and if there are any arguments, they are treated like path wildcards. Files resulting from that wildcards expansion are scanned for mocks. However, in the above case, the `--trace` argument is clearly not a file path, so no files are scanned for mocks, but all tests will run.

Possible fix ideas:
* When the wildcards expansion results in empty list, fall back to the default wildcard pattern `"test/**/*.exs"`. This still won't fix situations like `mix test --exclude test/my_test.exs`. In that case, all tests except for `test/my_test.exs` will run, but mocks will be looked for only in the `test/my_test.exs`.
* Dig into ExUnit and find out if it's possible to hook into it to get the list of tests to be run before they actually run.

What do you think?

**Comment by naag** [comment]
Just FYI: we're running into the same issue and are currently starting ExUnit with `ExUnit.start(trace: true)` as a workaround. That way we don't need to pass any arguments to `mix test`.

**Comment by ukrbublik** [comment]
+1
Why not just use config for `test_file_patterns` instead of system args?

**Comment by archan937** [comment]
Sorry for the embarrassingly late reply @hrubi, @naag and @ukrbublik.
But the fix has been release in MecksUnit v0.1.9 ✌️
